version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tingeso
    ports:
      - "33062:3306"
    volumes:
      - db_data:/var/lib/mysql

  app1:
    container_name: springboot-app1
    image: leonardom20/tingeso_entrega_1
    ports:
      - "8091:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tingeso?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  app2:
    image: leonardom20/tingeso_entrega_1
    container_name: springboot-app2
    ports:
      - "8092:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tingeso?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
volumes:
  db_data:
