version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tingeso
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tingeso?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tingeso?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2

volumes:
  db_data:
